import React from 'react';import {AbsoluteFill,Sequence,Img,Audio,staticFile,useCurrentFrame,interpolate,Easing} from 'remotion';import {Scene} from './Main';import {PageCam} from './PageCam';import COPY from './copy.json';import {beatF,SHOTS} from './timeline';
const INK='#161514',PAPER='#f4efe7',ORANGE='#f07848';
const P=(f:number,a:number,b:number,x:number,y:number)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.33,0,.15,1)});
import CLIPCOPY from './growth-copy.json';
const COPYCLIP:any=CLIPCOPY;
export const CLIP_TOTAL=beatF(52);
export const clipTotal=(kind:string)=>beatF(kind==='podcast'?36:52);
function AgentProof(){const f=useCurrentFrame();const id=f<beatF(8)?'sessions':f<beatF(14)?'session-copy':'resume-proof';return <PageCam src={`textures/live/${id}.png`} pageH={1000} keys={[{frame:0,cx:1490,cy:265,zoom:1.42},{frame:beatF(14),cx:880,cy:445,zoom:1},{frame:beatF(36),cx:880,cy:445,zoom:1}]}/>;}
function Hook({lang,kind}:{lang:string;kind:string}){const f=useCurrentFrame(),c=COPYCLIP[lang]||COPYCLIP.en;return <AbsoluteFill style={{background:PAPER,color:INK,justifyContent:'center',padding:100,fontFamily:'Arial,sans-serif'}}><div style={{fontSize:30,color:ORANGE,marginBottom:32}}>browsa / {c.cta}</div><div style={{fontSize:78,lineHeight:1.15,maxWidth:1650,fontWeight:600,letterSpacing:-2,opacity:P(f,0,16,0,1),transform:`translateY(${P(f,0,16,30,0)}px)`}}>{c[kind][0]}</div><div style={{fontSize:36,marginTop:34,color:'#6d5b4d'}}>{c[kind][1]}</div></AbsoluteFill>}
function Close({lang}:{lang:string}){const c=COPYCLIP[lang]||COPYCLIP.en;return <AbsoluteFill style={{background:PAPER,color:INK,justifyContent:'center',alignItems:'center',fontFamily:'Arial,sans-serif'}}><div style={{fontFamily:'Georgia,serif',fontSize:150,fontWeight:600,letterSpacing:-6}}>browsa<span style={{color:ORANGE}}>●</span></div><div style={{fontSize:35,marginTop:28}}>{(COPY as any)[lang].brandTag}</div><div style={{fontSize:34,color:'#7e6c5b',marginTop:24}}>github.com/xiaohuzai/browsa</div></AbsoluteFill>}
function Tech({lang}:{lang:string}){const f=useCurrentFrame(),live=lang==='zh',c=COPYCLIP[lang]||COPYCLIP.en,id=f<beatF(7)?'attached':f<beatF(11)?'typed':f<beatF(26)?'answer':'followup';return <AbsoluteFill style={{background:INK,color:PAPER}}><PageCam src={live?`textures/live/${id}.png`:`textures/${lang}/${f<beatF(11)?'typed':f<beatF(26)?'answer':'followup'}.png`} pageH={1000} keys={[{frame:0,cx:880,cy:470,zoom:.95},{frame:beatF(10),cx:1420,cy:355,zoom:1.60},{frame:beatF(36),cx:1420,cy:355,zoom:1.60}]}/><div style={{position:'absolute',inset:0,background:'linear-gradient(0deg,#161514 0%,#161514e0 16%,#16151400 38%)'}}/><div style={{position:'absolute',left:85,bottom:100,fontSize:60,fontFamily:'Arial,sans-serif'}}>{f<beatF(12)?c.attach:c.followup}</div><div style={{position:'absolute',right:85,bottom:30,fontSize:19,color:'#a89b8b'}}>{live?c.live:c.demo}</div></AbsoluteFill>}
export const GrowthClip:React.FC<{lang?:string;kind?:string;bgm?:boolean}>=({lang='zh',kind='tech',bgm=true})=><AbsoluteFill style={{background:INK}}><Sequence from={0} durationInFrames={beatF(8)}><Hook lang={lang} kind={kind}/></Sequence>{kind==='tech'?<Sequence from={beatF(8)} durationInFrames={beatF(36)}><Tech lang={lang}/></Sequence>:kind==='podcast'?<Sequence from={beatF(8)} durationInFrames={beatF(20)}><Scene lang={lang} index={SHOTS.findIndex(s=>s.id==='podcast')}/></Sequence>:lang==='zh'?<Sequence from={beatF(8)} durationInFrames={beatF(36)}><AgentProof/></Sequence>:<><Sequence from={beatF(8)} durationInFrames={beatF(8)}><Scene lang={lang} index={SHOTS.findIndex(s=>s.id==='sessions')}/></Sequence><Sequence from={beatF(16)} durationInFrames={beatF(28)}><Scene lang={lang} index={SHOTS.findIndex(s=>s.id==='relay')}/></Sequence></>}<Sequence from={beatF(kind==='podcast'?28:44)} durationInFrames={beatF(8)}><Close lang={lang}/></Sequence>{bgm?<Audio src={staticFile('audio/cat-walk.wav')} volume={f=>.72*interpolate(f,[0,5,clipTotal(kind)-30,clipTotal(kind)],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}/>:null}{kind==='podcast'||kind==='tech'||kind==='agent'?<Sequence from={beatF(kind==='agent'&&lang==='zh'?16:19)-1} durationInFrames={8}><Audio src={staticFile('audio/click-fixed.mp3')} volume={.65}/></Sequence>:null}</AbsoluteFill>;
