import React from 'react';
import {AbsoluteFill,Sequence,Img,Audio,staticFile,useCurrentFrame,interpolate,Easing} from 'remotion';
import {PageCam,CamKey} from './PageCam';
import COPY from './copy.json';import BOUNDS from './bounds.json';
import CONVERSATION from './conversation.json';
import {SHOTS,SFX,TOTAL,TRANSITION,beatF,localBeat} from './timeline';
const PAPER='#F4EFE7',INK='#161514',ORANGE='#F07848',MUTED='#a69a8a';
const ease=Easing.bezier(.33,0,.15,1),fly=Easing.bezier(.34,1.4,.44,1);
const p=(f:number,a:number,b:number,x=0,y=1,e=ease)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:e});
const font=(lang:string)=>lang==='zh'?"'Noto Sans SC','PingFang SC',sans-serif":lang==='ja'?"'Hiragino Sans',sans-serif":lang==='ko'?"'Apple SD Gothic Neo',sans-serif":"'Helvetica Neue',Arial,sans-serif";
const texture=(l:string,n:string)=>`textures/${l}/${n}.png`;
function Cursor({f,target,at}:{f:number;target:any;at:number}){if(!target||f<at-18||f>at+10)return null;const x=target.x+target.width/2,y=target.y+target.height/2;const t=p(f,at-18,at-2);return <><svg width={32} height={38} viewBox="0 0 24 28" style={{position:'absolute',left:x-5+(1-t)*48,top:y-4+(1-t)*32,filter:'drop-shadow(0 2px 2px #0009)'}}><path d="M4 2 20 15l-7 1 4 9-3 1-4-9-6 5z" fill={PAPER} stroke={INK} strokeWidth="1.2"/></svg>{f>=at?<div style={{position:'absolute',left:x-16,top:y-16,width:32,height:32,border:'2px solid '+ORANGE,borderRadius:50,opacity:p(f,at,at+10,.9,0),transform:`scale(${p(f,at,at+10,1,2)})`}}/>:null}</>}
function Footer({c,index,lang,title,sub}:{c:any;index:number;lang:string;title?:string;sub?:string}){const t=c.inkTitles[SHOTS[index].id];return <><div style={{position:'absolute',left:74,top:44,fontSize:24,fontWeight:600,color:ORANGE}}>browsa<span style={{color:PAPER,marginLeft:8}}>●</span></div><div style={{position:'absolute',right:74,top:48,fontSize:18,color:MUTED,letterSpacing:2}}>{String(index+1).padStart(2,'0')} / {t.kicker}</div><div style={{position:'absolute',left:74,right:['math','mermaid','dot','protein','chemistry','byok','followup','context'].includes(SHOTS[index].id)?1120:74,bottom:79}}><div style={{fontSize:lang==='ru'||lang==='es'?56:60,fontWeight:500,letterSpacing:-1.2,lineHeight:1.16}}>{title||t.title}</div><div style={{fontSize:34,color:'#c5baac',marginTop:15,lineHeight:1.28}}>{sub||t.sub}</div></div><div style={{position:'absolute',left:74,bottom:25,fontSize:15,color:MUTED}}>CHROME / EDGE</div><div style={{position:'absolute',right:74,bottom:25,fontSize:15,color:MUTED}}>{c.disclaimer}</div></>}
export const Scene:React.FC<{lang?:string;index?:number;title?:string;sub?:string}>=({lang='zh',index=0,title,sub})=>{const f=useCurrentFrame(),s=SHOTS[index],c=(COPY as any)[lang],b=(BOUNDS as any)[lang];const lb=(n:number)=>localBeat(index,n);const get=(name:string)=>b.bounds[name];const id=s.id,cb=(CONVERSATION as any)[lang]?.bounds||{};let image='empty',keys:CamKey[]=[{frame:0,cx:880,cy:465,zoom:.9}],target:any=null,at=0;
 if(id==='intro'){image='empty';keys=[{frame:0,cx:880,cy:480,zoom:.87,rotY:-6,rotX:2},{frame:lb(5),cx:880,cy:480,zoom:.87,rotY:-6,rotX:2},{frame:lb(8),cx:1180,cy:360,zoom:1.02,rotY:0,rotX:0},{frame:lb(10),cx:1020,cy:430,zoom:.96,rotY:0,rotX:0}];target={x:1650,y:58,width:45,height:45};at=lb(7);}
 if(id==='read'){image=f<lb(2)?'empty':f<lb(5)?'attached':f<lb(7)?'typed':'answer';keys=[{frame:0,cx:1020,cy:430,zoom:.96},{frame:lb(2),cx:1330,cy:940,zoom:1.36},{frame:lb(4),cx:1330,cy:940,zoom:1.36},{frame:lb(6),cx:1510,cy:940,zoom:1.36},{frame:lb(8),cx:1320,cy:330,zoom:1.65},{frame:lb(12),cx:1320,cy:330,zoom:1.65}];target=f<lb(5)?get('empty:#attach'):get('typed:#send');at=f<lb(5)?lb(2):lb(7);}
 if(id==='byok'){image=f<lb(4)?'byok-llm':'byok-agent';keys=[{frame:0,cx:545,cy:620,zoom:1.15},{frame:lb(4),cx:545,cy:620,zoom:1.15},{frame:lb(8),cx:545,cy:620,zoom:1.15}];}
 if(id==='followup'){image=f<lb(2)?'follow-selected':f<lb(5)+6?'follow-typed':'follow-answer';keys=[{frame:0,cx:1130,cy:400,zoom:1.3},{frame:lb(6),cx:1130,cy:430,zoom:1.3},{frame:lb(10),cx:1130,cy:430,zoom:1.3}];target=f<lb(3)?cb['follow-selected:.selection-ask-btn']:cb['follow-typed:.detail-thread-send'];at=f<lb(3)?lb(2):lb(5);}
 if(id==='context'){image=f<lb(1)?'agent-before':f<lb(3)+6?'agent-menu':f<lb(5)+8?'agent-choice':f<lb(8)+6?'agent-typed':'agent-answer';keys=[{frame:0,cx:1130,cy:420,zoom:1.3},{frame:lb(5)+8,cx:1130,cy:470,zoom:1.3},{frame:lb(6),cx:1130,cy:730,zoom:1.3},{frame:lb(8)+6,cx:1130,cy:730,zoom:1.3},{frame:lb(10),cx:1130,cy:470,zoom:1.3},{frame:lb(14),cx:1130,cy:470,zoom:1.3}];target=f<lb(2)?cb['agent-before:#provider']:f<lb(4)?{x:cb['agent-menu:#provider'].x+10,y:cb['agent-menu:#provider'].y+48,width:cb['agent-menu:#provider'].width-20,height:20}:f<lb(6)?cb['agent-choice:.provider-switch-card button:first-child']:cb['agent-typed:#send'];at=f<lb(2)?lb(1):f<lb(4)?lb(3):f<lb(6)?lb(5):lb(8);}
 if(id==='podcast'){image=f<lb(3)?'video':f<lb(11)?'timeline':f<lb(15)?'timeline-seek':'video-seek';keys=[{frame:0,cx:950,cy:490,zoom:.9},{frame:lb(4),cx:1540,cy:355,zoom:1.5},{frame:lb(10),cx:1540,cy:355,zoom:1.5},{frame:lb(15),cx:800,cy:620,zoom:1.12},{frame:lb(20),cx:800,cy:620,zoom:1.12}];target=get('timeline:.ts-row[data-s="462"]');at=lb(11);}
 if(id==='take'){image=f<lb(2)?'take':f<lb(6)?'copied':f<lb(7)?'diagram-download':'diagram-downloaded';keys=[{frame:0,cx:1430,cy:370,zoom:1.50},{frame:lb(5),cx:1430,cy:370,zoom:1.50},{frame:lb(7),cx:1470,cy:290,zoom:1.55},{frame:lb(12),cx:1470,cy:290,zoom:1.55}];target=f<lb(6)?get('copy-button'):{x:1720,y:253,width:26,height:26};at=f<lb(6)?lb(2):lb(7);}
 if(id==='sessions'){image=f<lb(2)?'copied':f<lb(3)+6?'sessions':'session-restored';keys=[{frame:0,cx:1430,cy:420,zoom:1.25},{frame:lb(2),cx:1470,cy:420,zoom:1.25},{frame:lb(5),cx:1430,cy:420,zoom:1.25},{frame:lb(8),cx:1430,cy:420,zoom:1.25}];target=f<lb(2.5)?get('sessions-button'):b.rows[0];at=f<lb(2.5)?lb(2):lb(3);}
 if(id==='relay'){image=f<lb(1)?'multi-agents':f<lb(2)?'agent-switch':f<lb(3)?'sessions':'session-copy';keys=[{frame:0,cx:1460,cy:235,zoom:1.4},{frame:lb(4),cx:1460,cy:235,zoom:1.4}];target=get('agent-copy');at=lb(3);}
 if(id.startsWith('chapter-'))return <Chapter lang={lang} c={c} chapter={id==='chapter-read'?0:id==='chapter-video'?1:id==='chapter-continue'?2:3} f={f}/>;
 const rich=['math','mermaid','dot','protein','chemistry'].includes(id);
 return <AbsoluteFill style={{background:INK,color:PAPER,fontFamily:font(lang),overflow:'hidden'}}>
 {rich?<PanelRender lang={lang} index={index} f={f}/>:id==='outro'?<Outro lang={lang} c={c} f={f}/>:<>
 <PageCam src={texture(lang,id==='take'&&f>=lb(6)?(f<lb(7)?'native-download':'native-downloaded'):image)} pageH={id==='take'&&f>=lb(6)?1228:1000} keys={id==='take'&&f>=lb(6)?[{frame:lb(6),cx:870,cy:614,zoom:.86},{frame:lb(9),cx:1430,cy:420,zoom:1.25}]:keys}>
 {id==='intro'&&f<lb(7)?<div style={{position:'absolute',left:1100,top:108,width:660,height:892,background:INK}}/>:null}{(id!=='sessions'||f<lb(3)+6)&&(id!=='context'||((f<lb(3)+6||f>=lb(4))&&(f<lb(5)+8||f>=lb(6))))&&(id!=='followup'||f<lb(5)+6)?<Cursor f={f} target={target} at={at}/>:null}
 </PageCam>
 {id==='intro'&&f<lb(6)?<AbsoluteFill style={{background:PAPER,color:INK,opacity:p(f,lb(5),lb(6),1,0),justifyContent:'center',alignItems:'center'}}><div style={{textAlign:'center'}}><div style={{fontFamily:'Georgia,serif',fontSize:145,fontWeight:600,letterSpacing:-5,display:'flex',justifyContent:'center'}}>{'browsa'.split('').map((ch,i)=>{const q=p(f,4+i*3,17+i*3);return <span key={i} style={{opacity:q,transform:`scale(${1.6-.6*q})`,filter:`blur(${(1-q)*6}px)`,transformOrigin:'center bottom'}}>{ch}</span>})}<span style={{color:ORANGE,fontSize:68,alignSelf:'end',paddingBottom:12}}>●</span></div><div style={{height:4,width:200,background:ORANGE,margin:'30px auto',transform:`scaleX(${p(f,20,34)})`}}/><div style={{fontSize:34,opacity:p(f,20,36),maxWidth:1500,lineHeight:1.5}}>{c.introline||c.brandTag}</div><div style={{fontSize:34,color:'#78685a',marginTop:20,opacity:p(f,25,40)}}>{c.identity}</div></div></AbsoluteFill>:null}
 {id==='relay'?<Relay c={c} lang={lang} f={f} start={lb(4)} end={lb(6)}/>:null}
 </>}
 {id!=='outro'?<><div style={{opacity:id==='intro'&&f<lb(6)?0:1,position:'absolute',top:0,bottom:0,left:0,right:rich||['byok','followup','context'].includes(id)?1120:0,background:rich||['byok','followup','context'].includes(id)?'linear-gradient(0deg,#161514 0%,#161514f9 30%,#16151400 55%)':'linear-gradient(0deg,#161514 0%,#161514f9 12%,#16151400 28%)',pointerEvents:'none'}}/>{id!=='intro'||f>=lb(6)?<Footer c={c} index={index} lang={lang} title={title} sub={sub}/>:null}</>:null}
 </AbsoluteFill>;
};
function Chapter({lang,c,chapter,f}:{lang:string;c:any;chapter:number;f:number}){
 const n=chapter,t=c.chapterCards[n],q=p(f,0,14);
 return <AbsoluteFill style={{background:PAPER,color:INK,fontFamily:font(lang),justifyContent:'center',padding:'100px 150px'}}>
 <div style={{position:'absolute',top:70,left:150,fontSize:26,color:'#9b613f'}}>browsa <span style={{color:ORANGE}}>●</span></div>
 <div style={{display:'flex',alignItems:'center',gap:35,opacity:q,transform:`translateY(${(1-q)*22}px)`}}>
 <div style={{fontSize:112,fontFamily:'Georgia,serif',color:ORANGE,lineHeight:1}}>0{n+1}</div>
 <div style={{width:3,height:96,background:'#d4bda5'}}/>
 <div style={{fontSize:chapter>=2?(lang==='ru'?64:lang==='zh'?78:68):(lang==='ru'?84:94),fontWeight:500,letterSpacing:-2,lineHeight:1.14}}>{t[0]}</div></div>
 <div style={{fontSize:34,color:'#776b5f',marginTop:34,marginLeft:175,opacity:q}}>{t[1]}</div>
 <div style={{width:180,height:4,background:ORANGE,margin:'36px 0 30px 175px',transform:`scaleX(${q})`,transformOrigin:'left'}}/>
 <div style={{fontSize:38,marginLeft:175,lineHeight:1.4,opacity:q,maxWidth:1450}}>{t[2]}</div>
 </AbsoluteFill>;
}
function PanelRender({lang,index,f}:{lang:string;index:number;f:number}){
 const id=SHOTS[index].id,short=id==='protein'||id==='chemistry';
 if(id==='math'||id==='dot'){
  const cam=id==='math'?{cx:1065,cy:480,zoom:1.15}:{cx:870,cy:614,zoom:.86};
  return <PageCam src={texture(lang,'native-'+id)} pageH={1228} keys={[{frame:0,...cam},{frame:SHOTS[index].duration,...cam}]}/>;
 }
 const cam=id==='mermaid'?{cx:1116,cy:560,zoom:1.02}:{cx:1159,cy:455,zoom:1.18};
 const image=id==='protein'&&f>localBeat(index,1)?'protein-rotated':id;
 return <PageCam src={texture(lang,image)} pageH={1000} keys={[{frame:0,...cam},{frame:SHOTS[index].duration,...cam}]}/>;
}
function Relay({c,lang,f,start,end}:{c:any;lang:string;f:number;start:number;end:number}){const t=p(f,start,end,0,1,Easing.inOut(Easing.cubic));return <div style={{position:'absolute',left:1920*(1-t),top:110,width:1920,height:710,background:INK}}><svg style={{position:'absolute',left:-1920,top:200,width:3840,height:240}}><path d="M480 20 H3440 V190 H2350 V20" fill="none" stroke={ORANGE} strokeWidth={6} strokeDasharray={4400} strokeDashoffset={4400*(1-p(f,start,end+12))}/></svg><div style={{position:'absolute',left:230,top:90,width:1460,height:500,border:'1px solid #655546',borderRadius:14,background:'#1c1a18',padding:'34px 46px',opacity:p(f,end-5,end+12)}}><div style={{display:'flex',justifyContent:'space-between',fontSize:34,color:ORANGE}}><span>Codex</span><span>DEMO · {c.agentDemoLabel||c.disclaimer}</span></div><div style={{fontSize:30,fontFamily:'Menlo,monospace',lineHeight:1.7,marginTop:34}}><span style={{color:'#a2998c'}}>$ </span>codex resume<br/><span style={{color:ORANGE}}>0199-demo-4820-browsa-transformer</span></div><div style={{borderTop:'1px solid #4c4035',paddingTop:22,marginTop:24,fontSize:31,lineHeight:1.4}}>{c.continueQ}</div><div style={{fontSize:22,color:'#a99b8b',marginTop:20}}>{c.relayContext||c.inkTitles.relay.sub}</div></div></div>}
function Outro({lang,c,f}:{lang:string;c:any;f:number}){const enter=p(f,0,32),items=[['crop-math',-560,-260,-7],['crop-mermaid',560,-230,6],['crop-dot',-560,265,5],['crop-take',550,265,-5]];return <AbsoluteFill style={{background:PAPER,color:INK}}>{items.map(([src,x,y,rot],i)=>{const q=p(f,i*4,i*4+20,0,1,fly);return <div key={i} style={{position:'absolute',left:960+Number(x)-230,top:490+Number(y)-110,width:460,height:220,borderRadius:16,overflow:'hidden',boxShadow:'0 12px 34px #5e443426',opacity:.7*q,transform:`translate(${Number(x)*(1-q)}px,${Number(y)*(1-q)}px) rotate(${rot}deg) scale(${.8+.2*q})`}}><Img src={staticFile(texture(lang,String(src)))} style={{width:'100%',height:'100%',objectFit:'contain',background:INK}}/></div>})}<AbsoluteFill style={{background:'radial-gradient(ellipse at center,#f4efe7 15%,#f4efe7ee 29%,#f4efe700 75%)',alignItems:'center',justifyContent:'center'}}><div style={{textAlign:'center',transform:`translateY(${(1-enter)*30}px)`,opacity:enter}}><div style={{fontFamily:'Georgia,serif',fontSize:155,letterSpacing:-6,fontWeight:600}}>browsa<span style={{color:ORANGE,fontSize:65}}>●</span></div><div style={{height:4,width:230,margin:'20px auto 27px',background:ORANGE}}/><div style={{fontSize:lang==='ru'?45:51,fontWeight:500}}>{c.inkTitles.outro.title}</div><div style={{fontSize:34,color:'#796b5c',marginTop:23}}>{c.identity}</div><div style={{fontSize:34,color:'#9b613d',marginTop:28}}>github.com/xiaohuzai/browsa</div></div></AbsoluteFill></AbsoluteFill>}
export const Main:React.FC<{lang?:string;bgm?:boolean;voice?:boolean}>=({lang='zh',bgm=true})=><AbsoluteFill style={{background:INK}}>{SHOTS.map((s,i)=><Sequence key={s.id} from={s.from} durationInFrames={s.duration+(i<SHOTS.length-1?TRANSITION:0)} premountFor={15}><div style={{position:'absolute',inset:0}}><WrappedScene lang={lang} index={i}/></div></Sequence>)}{bgm?<Audio src={staticFile('audio/cat-walk.wav')} volume={.72}/>:null}{SFX.map(s=><Sequence key={s.event} from={s.from} durationInFrames={s.duration}><Audio src={staticFile('audio/'+s.src)} volume={s.volume}/></Sequence>)}</AbsoluteFill>;
export const WrappedScene:React.FC<{lang?:string;index?:number;title?:string;sub?:string}>=(props)=><Fade index={props.index||0}><Scene {...props}/></Fade>;
function Fade({index,children}:{index:number;children:React.ReactNode}){const f=useCurrentFrame();return <AbsoluteFill style={{opacity:index===0?1:p(f,0,TRANSITION,0,1,Easing.linear)}}>{children}</AbsoluteFill>}
