import {chromium} from 'playwright-core';
import {attentionMath,attentionMermaid,encoderDot} from './transformer-example7.mjs';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {join,resolve} from 'node:path';import assert from 'node:assert/strict';
const ROOT=resolve(import.meta.dirname,'../../../..'),COPY=JSON.parse(readFileSync(join(import.meta.dirname,'copy-v7.json'))),OUT=join(ROOT,'store-assets/promo/v7/assets');
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{for(const lang of (process.argv.slice(2).length?process.argv.slice(2):Object.keys(COPY))){const c=COPY[lang],dir=join(OUT,lang);mkdirSync(dir,{recursive:true});const ctx=await browser.newContext({viewport:{width:1760,height:1000},deviceScaleFactor:2,colorScheme:'dark',acceptDownloads:true}),outer=await ctx.newPage();const report=process.env.PROMO_TAKE_ONLY||process.env.PROMO_RENDER_ONLY?JSON.parse(readFileSync(join(dir,'capture.json'))):{lang,checks:[],bounds:{},errors:[]};outer.on('pageerror',e=>report.errors.push(e.message));
await ctx.addInitScript(()=>{window.__copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>{window.__copied.push(t);}},configurable:true});});
await ctx.route('https://files.rcsb.org/download/1LYZ.pdb',route=>route.fulfill({body:readFileSync(join(ROOT,'store-assets/promo/v7/1LYZ.pdb')),contentType:'text/plain'}));
let page;
const load=async()=>{await outer.goto('http://127.0.0.1:8957/browser-v7.html');await outer.evaluate(([c,l])=>window.init(c,l,'read'),[c,lang]);await outer.waitForTimeout(600);page=outer.frames().find(f=>f.url().includes('sidepanel.preview'));await page.waitForSelector('#input');await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(async()=>(await import('/repo/lib/i18n.js')).currentUiLang()),lang==='pt-BR'?'pt':lang);};
const snap=async(name,selectors=[])=>{await page.evaluate(()=>document.querySelectorAll('textarea,input').forEach(e=>e.blur()));await outer.screenshot({path:join(dir,name+'.png')});for(const s of selectors){const b=await page.locator(s).last().boundingBox();if(b)report.bounds[name+':'+s]=b;}};
const send=async(q,a)=>{await page.locator('#input').fill(q);await page.locator('#send').click();await outer.waitForTimeout(200);await page.evaluate(t=>{const p=window.__promoPorts['browsa-chat'];p.__push({type:'CHUNK',delta:t});p.__push({type:'DONE',full:t,providerLabel:'Agent Bridge · codex',providerKey:{name:'bridge',model:'http://127.0.0.1:3948'}});},a);await outer.waitForTimeout(700);await page.evaluate(()=>document.querySelector('#messages').scrollTop=0);};
if(!process.env.PROMO_TAKE_ONLY){if(!process.env.PROMO_RENDER_ONLY){await load();await snap('empty',['#attach','#input','#provider']);await page.locator('#attach').click();await outer.waitForTimeout(300);await snap('attached',['#send']);await page.locator('#input').fill(c.q1);await snap('typed',['#send']);await page.locator('#send').click();await outer.waitForTimeout(200);await page.evaluate(t=>{const p=window.__promoPorts['browsa-chat'];p.__push({type:'CHUNK',delta:t});p.__push({type:'DONE',full:t,providerLabel:'Agent Bridge · codex',providerKey:{name:'bridge',model:'http://127.0.0.1:3948'}});},c.a1);await outer.waitForTimeout(700);await page.evaluate(()=>document.querySelector('#messages').scrollTop=0);await snap('answer',['.msg.assistant']);report.checks.push('real attach/send localized answer');
}
const l=c.richLabels;const cases=[['math',attentionMath+'\n\n'+c.mathNote,'#messages .katex'],['mermaid','```mermaid\n'+attentionMermaid+'\n```','.mermaid-diagram svg'],['dot','```dot\n'+encoderDot(l)+'\n```','.dot-diagram svg'],['protein','```pdb\n1LYZ\n```\n\n'+c.proteinNote,'.pdb-viewer canvas'],['chemistry','```smiles\nCC(=O)NCC(=O)O.O>>CC(=O)O.NCC(=O)O\n```\n\n'+c.chemistryNote,'.smiles-svg']];
for(let i=0;i<cases.length;i++){const [name,answer,selector]=cases[i];await load();await send(c.renderQ[i],answer);await page.waitForSelector(selector,{timeout:60000});if(name==='protein')await page.waitForSelector('.pdb-viewer .mermaid-toolbar',{timeout:60000});await outer.waitForTimeout(name==='protein'?1600:600);await snap(name,['.msg.assistant',selector]);if(name==='protein'){const canvas=page.locator(selector),b=await canvas.boundingBox();await outer.mouse.move(b.x+b.width*.5,b.y+b.height*.55);await outer.mouse.down();await outer.mouse.move(b.x+b.width*.75,b.y+b.height*.50,{steps:12});await outer.mouse.up();await outer.waitForTimeout(300);await snap('protein-rotated');report.checks.push('actual Molstar 1LYZ WebGL rotation');}if(name==='mermaid'){await page.locator('.mermaid-diagram').hover();await snap('diagram-download',['.mermaid-toolbar button']);const downloadButton=page.locator('.mermaid-toolbar button').filter({hasText:'↓'});report.bounds['download-button']=await downloadButton.boundingBox();await snap('diagram-download',['.mermaid-toolbar button']);const [d]=await Promise.all([outer.waitForEvent('download'),downloadButton.click()]);await d.saveAs(join(dir,'attention-pathway.png'));await snap('diagram-downloaded');report.checks.push('native diagram download '+d.suggestedFilename());}}
}
if(!process.env.PROMO_RENDER_ONLY){await load();await page.locator('#provider').selectOption({label:(await page.locator('#provider option').allTextContents()).find(x=>x.includes('codex'))});await send(c.agentQ,c.finalAnswer);await page.locator('.msg.assistant').last().hover();const label=await page.evaluate(async()=>(await import('/repo/lib/i18n.js')).t('copyResponseTitle'));const actual=page.locator('.msg.assistant button[title='+JSON.stringify(label)+']');await actual.hover();await snap('take',['.msg.assistant']);report.bounds['copy-button']=await actual.boundingBox();await page.locator('.msg.assistant').last().hover();await actual.click();await outer.waitForTimeout(120);assert.ok((await page.evaluate(()=>window.__copied)).some(t=>t===c.finalAnswer));await snap('copied');report.checks.push('whole native answer copy equals original');}report.errors=report.errors.filter(e=>!e.includes('WebGL'));assert.deepEqual(report.errors,[]);writeFileSync(join(dir,'capture.json'),JSON.stringify(report,null,2));console.log(lang,report.checks);await ctx.close();}}finally{await browser.close();}
