import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,cpSync,renameSync,existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
const HERE=import.meta.dirname,ROOT=resolve(HERE,'../../../..'),ASSETS=join(ROOT,'store-assets/promo/v5/assets'),OUT=join(ROOT,'store-assets/promo/v7');
const COPY=JSON.parse(readFileSync(join(HERE,'src/copy.json')));const langs=process.argv.slice(2).filter(x=>!x.startsWith('--'));const still=process.argv.includes('--stills'),all=langs.length?langs:Object.keys(COPY);
mkdirSync(join(OUT,'qa'),{recursive:true});
if(!process.argv.includes('--stills')&&(!existsSync(join(OUT,'main-audio-shared.wav'))||!existsSync(join(OUT,'nobgm-shared.wav'))||process.argv.includes('--refresh-audio')))execFileSync(process.execPath,[join(HERE,'build-audio.mjs')],{stdio:'inherit'});
const cli=join(HERE,'node_modules/.bin/remotion');const port='--port='+(process.env.BROWSA_RENDER_PORT||'3100');
for(const lang of all){const slug=lang.toLowerCase();writeFileSync(join(OUT,'props-'+slug+'.json'),JSON.stringify({lang,bgm:true,voice:false}));
 if(still){for(const f of (process.env.BROWSA_QA_FRAMES?process.env.BROWSA_QA_FRAMES.split(',').map(Number):[55,145,250,390,495,610,720,835,960,1060,1210,1300,1400,1500,1610,1730,1771])){execFileSync(cli,['still',port,'src/index.ts','BrowsaPromo',join(OUT,'qa',slug+'-'+f+'.png'),'--frame='+f,'--props='+join(OUT,'props-'+slug+'.json')],{cwd:HERE,stdio:'inherit'});}continue;}
 const dest=join(ROOT,'docs/assets/promo','browsa-promo-v7-'+slug+'.mp4');if(!process.argv.includes('--reuse-video'))execFileSync(cli,['render',port,'src/index.ts','BrowsaPromo',dest,'--props='+join(OUT,'props-'+slug+'.json'),'--codec=h264','--crf=20','--concurrency=2','--gl=swiftshader','--muted'],{cwd:HERE,stdio:'inherit'});
 {const aw=join(OUT,'main-audio-shared.wav'),tmp=dest+'.tmp.mp4';if(!existsSync(aw))execFileSync(cli,['render',port,'src/index.ts','BrowsaPromo',aw,'--props='+join(OUT,'props-'+slug+'.json'),'--codec=wav'],{cwd:HERE,stdio:'inherit'});execFileSync('ffmpeg',['-y','-i',dest,'-i',aw,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-movflags','+faststart',tmp],{stdio:'inherit'});renameSync(tmp,dest);}
 writeFileSync(join(OUT,'props-'+slug+'-nobgm.json'),JSON.stringify({lang,bgm:false,voice:false}));const wav=join(OUT,'nobgm-shared.wav');if(!existsSync(wav))execFileSync(cli,['render',port,'src/index.ts','BrowsaPromo',wav,'--props='+join(OUT,'props-'+slug+'-nobgm.json'),'--codec=wav'],{cwd:HERE,stdio:'inherit'});execFileSync('ffmpeg',['-y','-i',dest,'-i',wav,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-movflags','+faststart',join(ROOT,'docs/assets/promo','browsa-promo-v7-'+slug+'-nobgm.mp4')],{stdio:'inherit'});
 execFileSync('ffmpeg',['-y','-ss','4.3','-i',dest,'-frames:v','1','-q:v','2',join(ROOT,'docs/assets/promo','poster-v7-'+slug+'.jpg')],{stdio:'inherit'});
 execFileSync('ffmpeg',['-y','-ss','0','-t','69','-i',dest,'-filter_complex',"[0:v]select='between(t,3.5,8.6)+between(t,12,16.5)+between(t,17.5,21)+between(t,23,28)+between(t,30.5,32.5)+between(t,36,39)+between(t,44,48)+between(t,52.5,54)+between(t,54.8,55.8)+between(t,61.5,64)',setpts=N/FRAME_RATE/TB,fps=10,scale=720:-1:flags=lanczos,fade=t=in:st=0:d=0.3,fade=t=out:st=31.8:d=0.3,split[a][b];[a]palettegen=max_colors=160:reserve_transparent=0:stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle:alpha_threshold=0",'-loop','0',join(ROOT,'docs/assets/readme','demo-v16-'+slug+'.gif')],{stdio:'inherit'});
}
